### PR TITLE
Date time

### PR DESCRIPTION
**Pull request by afsalthaj**

### CODE REVIEW

**Comment by afsalthaj** [comment]
Could someone review this ?:)

**Comment by wookietreiber** [comment]
I like the idea of adding an option to format the date.

I would advise, though, against introducing a new dependency.

**Comment by afsalthaj** [comment]
You would like to get rid off scalaz dependency?

**Comment by wookietreiber** [comment]
Yes, I would get rid of the scalaz dependency. This project hasn't been using this up to now and it would not be good to start using it now. Almost there will be people who would not like to pull in an additional dependency if that could be avoided.

Also, a date/time library does not necessarily need to depend on something like scalaz, especially a wrapper library like this one should be as small as possible.

**Comment by afsalthaj** [comment]
That really makes sense. My bad !! 
Il get rid off the this overhead soon.

**Comment by kmizu** [comment]
Hi.  I'm one of main committer of this project.  As @wookietreiber already said, scalaz dependency should be removed since nscala-time is just a wrapper library. Optional format param is nice, but this change introduces breaking changes for the users since additional "()" is needed.  It would be nice if the overloaded version is also prepared.

**Comment by afsalthaj** [comment]
@kmizu.. Thanks for pointing this out.  l will make a few changes such that it keeps backward compatibility.

**Comment by afsalthaj** [comment]
@wookietreiber @kmizu pls let me know if its ok for you to merge it. nscala-time will become so useful for our organization with these minor changes in place.  Also, I am happy to make further changes that you may advise

**Comment by kmizu** [comment]
@afsalthaj I saw the changes a couple of minutes ago and it's OK to merge.  Then, I merged it

**Comment by afsalthaj** [comment]
@kmizu is there any way u could publish the current version ? Instead of snapshot...

**Comment by kmizu** [comment]
@afsalthaj  BTW, I merged your PR which commit logs are too dirty accidently.  Please send the pull request in the next time after cleaning your commit logs using `git rebase`.  OK?

**Pull request merged**
